import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import WhatsAppButton from "../components/global/whatsappButton/WhatsappButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Jurídicos y Asociados",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
      <html lang="es">
        <body className={`${inter.className} bg-black text-white`}>
          {children}
        </body>
        <WhatsAppButton />
      </html>
  );
}
